export type CommandEntrancePath = string;

/** Static CLI primary-path baseline captured from the assembled Commander program. */
export const CLI_ENTRANCE_BASELINE: readonly CommandEntrancePath[] = [
  "acp",
  "acp list",
  "acp login",
  "acp test",
  "acp usage",
  "agent",
  "agent-mission",
  "agent-mission config-migrate",
  "agent-mission mission",
  "agent-mission models",
  "agent-mission review-loop",
  "agent-mission review-stats",
  "agent-mission review-watch",
  "agent-mission setup",
  "ask",
  "attach",
  "autopilot",
  "autopilot add-phase",
  "autopilot approve",
  "autopilot arm",
  "autopilot briefing",
  "autopilot cancel",
  "autopilot check",
  "autopilot decide",
  "autopilot decompose-crash",
  "autopilot decompose-stream",
  "autopilot delete-arc",
  "autopilot delete-phase",
  "autopilot escalate",
  "autopilot freshness",
  "autopilot history",
  "autopilot inject",
  "autopilot insert-arc",
  "autopilot insert-phase",
  "autopilot landing",
  "autopilot link",
  "autopilot list",
  "autopilot materialize",
  "autopilot maturity-split",
  "autopilot merge",
  "autopilot negotiate",
  "autopilot pause",
  "autopilot phases",
  "autopilot pipeline",
  "autopilot prepare-log",
  "autopilot promote",
  "autopilot rebuild",
  "autopilot reconcile",
  "autopilot redesign",
  "autopilot reorder-arc",
  "autopilot rereflect",
  "autopilot rerun",
  "autopilot resources",
  "autopilot restart-daemon",
  "autopilot resume",
  "autopilot review",
  "autopilot revise",
  "autopilot revise-suggest",
  "autopilot run",
  "autopilot signal",
  "autopilot skip",
  "autopilot split",
  "autopilot system-repair",
  "autopilot threads",
  "autopilot trace",
  "autopilot unlink",
  "buzz",
  "chat",
  "config",
  "config get",
  "config mission",
  "config mission get",
  "config mission mode",
  "config mission reset",
  "config mission set",
  "config path",
  "config promote",
  "config set",
  "config sync-test",
  "config unset",
  "dev",
  "discord-test",
  "docs",
  "docs revision",
  "docs search",
  "docs stale",
  "factcheck",
  "finance",
  "finance sector-flow",
  "fleet",
  "fleet list",
  "fleet screen",
  "gh",
  "git",
  "harness",
  "harness clean",
  "harness dogfood",
  "harness map",
  "harness orchestrate",
  "harness run",
  "harness run-detached",
  "harness terminals-purge",
  "harness verify-url",
  "harness worktree",
  "harness worktree add",
  "harness worktrees",
  "history",
  "inspect",
  "keys",
  "leader",
  "leader claim",
  "leader status",
  "local",
  "local bench",
  "local chat",
  "local inventory",
  "local models",
  "local pick",
  "local ping",
  "local scores",
  "local setup",
  "local test",
  "login",
  "login logout",
  "login openai-codex",
  "login status",
  "logs",
  "logs degenerate",
  "logs fields",
  "logs instances",
  "logs level",
  "logs timeline",
  "logs unclosed",
  "loops",
  "mcp",
  "mcp diagnose",
  "mcp serve",
  "memory",
  "memory add",
  "memory delete",
  "memory index",
  "memory list",
  "memory pin",
  "memory priority",
  "memory search",
  "memory show",
  "memory status",
  "memory unpin",
  "memory where",
  "measure-fabric-arc-ab",
  "nexus",
  "nexus build",
  "nexus channel-bot",
  "nexus channel-bot setup",
  "nexus config",
  "nexus config get",
  "nexus config list",
  "nexus config set",
  "nexus config unset",
  "nexus connect",
  "nexus dist",
  "nexus dist link",
  "nexus dist publish",
  "nexus install",
  "nexus ios-bind",
  "nexus list",
  "nexus pwa",
  "nexus pwa build",
  "nexus pwa dev",
  "nexus pwa global",
  "nexus pwa global clean",
  "nexus pwa global status",
  "nexus pwa restart",
  "nexus pwa share",
  "nexus pwa share disable",
  "nexus pwa share enable",
  "nexus pwa share status",
  "nexus pwa show",
  "nexus pwa start",
  "nexus pwa stop",
  "nexus pwa verify",
  "nexus remove",
  "nexus run",
  "nexus setup-firecrawl",
  "nexus show",
  "nexus status",
  "nexus stop",
  "nexus switch",
  "nexus uninstall",
  "ops",
  "ops build",
  "ops health",
  "ops mission",
  "ops mission-log",
  "ops status",
  "ops timeline",
  "pr",
  "pr land",
  "provider",
  "provider codex",
  "provider codex account",
  "provider codex account import",
  "provider codex account list",
  "provider codex reset-credits",
  "provider codex reset-credits list",
  "provider codex reset-credits observe",
  "provider codex reset-credits redeem",
  "provider codex status",
  "provider codex usage",
  "provider:restore",
  "provider:rotate",
  "provider:set",
  "provider:use",
  "pty",
  "pty auto",
  "pty find",
  "pty key",
  "pty lineage",
  "pty list",
  "pty reap",
  "pty release",
  "pty resize",
  "pty retire",
  "pty snapshot",
  "pty takeover",
  "pty text",
  "publish",
  "publish catalog",
  "publish file",
  "publish gc",
  "questions",
  "questions answer",
  "questions pending",
  "registry",
  "registry drift",
  "repl",
  "repro",
  "schedule",
  "schedule adopt",
  "schedule create",
  "schedule delete",
  "schedule disable",
  "schedule enable",
  "schedule inspect",
  "schedule list",
  "schedule migrate",
  "schedule release",
  "schedule unwrap",
  "schedule update",
  "schedule wrap",
  "scheduler",
  "self",
  "self author",
  "self capabilities",
  "self capability",
  "self clarify",
  "self clarify answer",
  "self clarify closure",
  "self clarify list",
  "self clarify pending",
  "self entrances",
  "self gate",
  "self git-discipline",
  "self goal-asks",
  "self goal-run",
  "self goal-test-scenarios",
  "self goal-run-search",
  "self goal-runs",
  "self goal-source-distribution",
  "self implement",
  "self ledger",
  "self ledger lint",
  "self log",
  "self merge-attribution",
  "self orchestrate",
  "self parked",
  "self participants",
  "self provision",
  "self recall",
  "self repair-signals",
  "self review",
  "self run",
  "self run-chain",
  "self run-ledger",
  "self running-runs",
  "self screen",
  "self send",
  "self typecheck",
  "self unfinished-runs",
  "self unfinished-runs-cleanup",
  "self utterance",
  "session",
  "session compact",
  "session context",
  "session delete",
  "session export",
  "session fork",
  "session link",
  "session list",
  "session new",
  "session open",
  "session purge",
  "session release",
  "session resume",
  "session search",
  "session show",
  "session subscribe",
  "session subscribers",
  "session takeover",
  "session turn",
  "session unsubscribe",
  "session watch",
  "setup",
  "signals",
  "status",
  "status-bar",
  "sync",
  "task",
  "telegram-test",
  "theme",
  "theme export",
  "theme list",
  "theme preview",
  "theme use",
  "tier",
  "tier list",
  "tier providers",
  "tier resolve",
  "usage",
  "voice",
  "voice nl-switch",
  "voice status",
  "voice suggest",
  "wf",
  "wf list",
  "wf node",
  "wf node list",
  "wf node search",
  "wf node spec",
  "wf run",
  "wf show",
  "wf suggest-next",
  "wf synth",
  "wf validate",
  "where"
];

export interface EntranceBaselineComparison {
  missing: CommandEntrancePath[];
  added: CommandEntrancePath[];
}

export interface EntranceBaselineEvaluation extends EntranceBaselineComparison {
  exitCode: 0 | 1;
}

/**
 * Compares an externally supplied baseline with Commander-tree entrances.
 * Missing baseline paths are regressions; added paths remain visible but pass.
 */
export function compareCommandEntranceBaseline(
  baseline: readonly CommandEntrancePath[],
  actualEntrances: readonly { path: readonly string[] }[],
): EntranceBaselineComparison {
  const actual = new Set(actualEntrances.map((entrance) => entrance.path.join(' ')));
  const expected = new Set(baseline);
  return {
    missing: [...expected].filter((path) => !actual.has(path)),
    added: [...actual].filter((path) => !expected.has(path)),
  };
}

/** Returns the command status derived from a supplied, static baseline comparison. */
export function evaluateCommandEntranceBaseline(
  baseline: readonly CommandEntrancePath[],
  actualEntrances: readonly { path: readonly string[] }[],
): EntranceBaselineEvaluation {
  const comparison = compareCommandEntranceBaseline(baseline, actualEntrances);
  return { ...comparison, exitCode: comparison.missing.length === 0 ? 0 : 1 };
}
