// 플릿 reduce — 여러 조각(self orchestrate 의 자식)이 낸 PR 브랜치를 «하나의 통합 브랜치»로 모으고,
// 변경 범위 게이트를 한 번 돌려 PR 하나로 낸다(fleet RFC «병합» 칸의 빈자리 · 로드맵 09-26 #4).
//
// 순서: 기준(origin/<base>)에서 임시 워크트리 → 조각 브랜치를 차례로 `merge --no-ff`
//   → 충돌이면 «그 조각 ⊕ 충돌 파일»을 이름으로 대고 병합을 되돌린 뒤 멈춘다(추측으로 풀지 않는다)
//   → 다 합쳐지면 `self gate --base <base>`(새 회귀만 빨강) → 통합 브랜치 푸시 → PR 하나(조각 PR 나열)
//   → 조각 PR 에 «통합 PR 로 대체됨» 코멘트(닫지는 않는다 — 사람 몫).
// ⛔ 조각 PR 을 main 에 따로 병합하지 않는다 — 그건 `--auto-merge` 의 일이고 reduce 는 «하나로»다.

import { spawnSync } from 'node:child_process';
import { mkdtempSync, rmSync, symlinkSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { debug } from '../debug/log.js';

export interface Shard { label: string; branch: string; prNumber?: number }

export interface RunResult { status: number | null; stdout: string; stderr: string }
export type Run = (cmd: string, args: readonly string[], cwd: string) => RunResult;

export const defaultRun: Run = (cmd, args, cwd) => {
  const r = spawnSync(cmd, [...args], { cwd, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  return { status: r.status, stdout: r.stdout ?? '', stderr: r.error ? String(r.error) : (r.stderr ?? '') };
};

export type ReduceOutcome =
  | { kind: 'conflict'; shard: Shard; files: string[]; merged: Shard[] }
  | { kind: 'gate-failed'; merged: Shard[]; gateTail: string }
  | { kind: 'dry-run'; merged: Shard[]; branch: string }
  | { kind: 'pr-opened'; merged: Shard[]; branch: string; prUrl: string };

export interface ReduceOptions {
  repoRoot: string;
  shards: Shard[];
  base?: string;
  /** 통합 브랜치 이름 — 기본 `reduce/<시각>`. */
  branch?: string;
  title?: string;
  /** 푸시·PR·코멘트를 하지 않는다(병합·게이트까지만). */
  dryRun?: boolean;
  /** 게이트를 건너뛴다(권하지 않음 — 시험·긴급). */
  skipGate?: boolean;
  run?: Run;
  log?: (line: string) => void;
}

function must(r: RunResult, what: string): string {
  if (r.status !== 0) throw new Error(`${what} 실패(rc=${r.status}): ${(r.stderr || r.stdout).trim().split('\n').slice(-3).join(' / ')}`);
  return r.stdout;
}

/** PR 번호들 → 조각(브랜치 = PR head). */
export function shardsFromPrs(prs: number[], repoRoot: string, run: Run = defaultRun): Shard[] {
  return prs.map((n) => {
    const out = must(run('gh', ['pr', 'view', String(n), '--json', 'number,headRefName,title,state'], repoRoot), `PR #${n} 조회`);
    const pr = JSON.parse(out) as { number: number; headRefName: string; title: string; state: string };
    if (pr.state !== 'OPEN') throw new Error(`PR #${n} 는 ${pr.state} 다 — 열린 조각만 합친다`);
    return { label: `#${pr.number} ${pr.title}`.slice(0, 120), branch: pr.headRefName, prNumber: pr.number };
  });
}

/** 오케스트레이터 결과 → reduce 할 조각: PR 을 열었고(`pr-opened`) 병합되지 않았고 브랜치가 있는 것만, 결과 순서대로. */
export function shardsFromResults(results: ReadonlyArray<{ feature: string; stage?: string; merged?: boolean; branch?: string; prNumber?: number; prUrl?: string }>): Shard[] {
  return results
    .filter((r) => r.stage === 'pr-opened' && !r.merged && Boolean(r.branch))
    .map((r) => {
      const n = r.prNumber ?? (r.prUrl ? Number(/\/pull\/(\d+)/.exec(r.prUrl)?.[1]) : undefined);
      return { label: r.feature.slice(0, 120), branch: r.branch!, ...(n !== undefined && Number.isFinite(n) ? { prNumber: n } : {}) };
    });
}

export function reduceBody(merged: Shard[], base: string, gate: string): string {
  return [
    `## 플릿 reduce — 조각 ${merged.length}개를 하나로`,
    '',
    `기준 \`${base}\` 위에 차례로 \`merge --no-ff\`:`,
    ...merged.map((s, i) => `${i + 1}. ${s.prNumber !== undefined ? `#${s.prNumber}` : s.branch} — ${s.label}`),
    '',
    `게이트(변경 범위 · 새 회귀만 빨강): ${gate}`,
    '',
    '조각 PR 은 닫지 않았다 — 이 PR 이 착지하면 사람이 닫는다(각 조각 PR 에 대체 코멘트를 남겼다).',
    '',
    '🤖 Generated by `elanous self reduce`',
  ].join('\n');
}

export async function reduceShards(opts: ReduceOptions): Promise<ReduceOutcome> {
  const run = opts.run ?? defaultRun;
  const log = opts.log ?? ((l: string) => console.log(l));
  const base = opts.base ?? 'main';
  const branch = opts.branch ?? `reduce/${new Date().toISOString().replace(/[-:]/g, '').slice(0, 15)}`;
  if (opts.shards.length < 2) throw new Error(`조각이 ${opts.shards.length}개다 — reduce 는 둘 이상을 하나로 모을 때만`);

  must(run('git', ['fetch', '-q', 'origin', base, ...opts.shards.map((s) => s.branch)], opts.repoRoot), 'git fetch');
  const wt = mkdtempSync(join(tmpdir(), 'elanous-reduce-'));
  rmSync(wt, { recursive: true, force: true });
  must(run('git', ['worktree', 'add', '-q', '-b', branch, wt, `origin/${base}`], opts.repoRoot), '통합 워크트리');
  const merged: Shard[] = [];
  let pushed = false;
  try {
    for (const shard of opts.shards) {
      const r = run('git', ['merge', '--no-ff', '--no-edit', '-m', `reduce: ${shard.label}`, `origin/${shard.branch}`], wt);
      if (r.status !== 0) {
        const files = run('git', ['diff', '--name-only', '--diff-filter=U'], wt).stdout.split('\n').filter(Boolean);
        run('git', ['merge', '--abort'], wt);
        debug.log('self-dev.reduce', 'conflict', { branch, shard: shard.branch, files, merged: merged.length });
        const against = merged.length === 0 ? `기준 origin/${base} 와 부딪힌다(조각이 만들어진 뒤 기준이 움직였다 — 그 조각을 먼저 기준 위로 올려야 한다)` : `앞서 합친 ${merged.length}개(${merged.map((s) => s.prNumber !== undefined ? `#${s.prNumber}` : s.branch).join(' · ')}) ⊕ 기준과 부딪힌다`;
        log(`⛔ 충돌 — ${shard.label} (${shard.branch}) 가 ${against}: ${files.join(', ') || '(파일 목록 못 읽음)'} — 풀지 않고 멈춘다`);
        return { kind: 'conflict', shard, files, merged };
      }
      merged.push(shard);
      log(`✓ 합침 ${merged.length}/${opts.shards.length} — ${shard.label}`);
    }
    let gate = '건너뜀(--skip-gate)';
    if (!opts.skipGate) {
      // 게이트는 저장소 코드로 돈다 — 통합 워크트리에 의존성을 잇는다(설치 없이).
      const nm = join(opts.repoRoot, 'node_modules');
      if (existsSync(nm) && !existsSync(join(wt, 'node_modules'))) symlinkSync(nm, join(wt, 'node_modules'));
      const g = run('bun', ['bin/elanous.mjs', 'self', 'gate', '--changed', '--base', `origin/${base}`], wt);   // 📏 `--changed` 가 없으면 rc 2 로 거절한다(첫 실물)
      const tail = `${g.stdout}\n${g.stderr}`.trim().split('\n').slice(-6).join('\n');
      if (g.status !== 0) {
        debug.log('self-dev.reduce', 'gate-failed', { branch, merged: merged.length, rc: g.status });
        log(`⛔ 통합 브랜치 게이트 실패(rc=${g.status}) — 조각은 각자 통과했지만 «합친 것»이 새 회귀를 낸다:\n${tail}`);
        return { kind: 'gate-failed', merged, gateTail: tail };
      }
      gate = `통과 — ${tail.split('\n').pop() ?? ''}`.trim();
    }
    if (opts.dryRun) {
      log(`· (dry-run) 통합 브랜치 ${branch} — 조각 ${merged.length}개 · 게이트 ${gate} · 푸시·PR 안 함`);
      return { kind: 'dry-run', merged, branch };
    }
    must(run('git', ['push', '-q', 'origin', `${branch}:${branch}`], wt), '통합 브랜치 푸시');
    pushed = true;
    const title = opts.title ?? `reduce: 조각 ${merged.length}개 통합 (${merged.map((s) => (s.prNumber !== undefined ? `#${s.prNumber}` : s.branch)).join(' · ')})`;
    const prUrl = must(run('gh', ['pr', 'create', '--base', base, '--head', branch, '--title', title, '--body', reduceBody(merged, `origin/${base}`, gate)], wt), 'PR 생성').trim().split('\n').pop() ?? '';
    for (const s of merged) {
      if (s.prNumber !== undefined) run('gh', ['pr', 'comment', String(s.prNumber), '--body', `🔀 이 조각은 통합 PR ${prUrl} 로 합쳐졌다(\`elanous self reduce\`). 그 PR 이 착지하면 이 PR 은 닫아도 된다.`], wt);
    }
    debug.log('self-dev.reduce', 'pr-opened', { branch, merged: merged.length, prUrl });
    log(`✅ 통합 PR ${prUrl} — 조각 ${merged.length}개 · 게이트 ${gate}`);
    return { kind: 'pr-opened', merged, branch, prUrl };
  } finally {
    run('git', ['worktree', 'remove', '--force', wt], opts.repoRoot);
    // 푸시하지 않은 통합 브랜치는 남기지 않는다(드라이런 · 충돌 · 게이트 실패) — 푸시했으면 PR 의 머리라 남긴다.
    if (!pushed) run('git', ['branch', '-D', branch], opts.repoRoot);
  }
}
