/**
 * FU8 follow-up #1 (2026-05-12 EoS #11) — KGS Mission entity card.
 *
 * Closes the loop opened by PR #8 (M4-3.2): workflows generated by
 * the intake pipeline already carry `_meta.missionId: 'mission:<id>'`
 * URN provenance, but until this module landed there was no KGS card
 * on the other side of that URN. This module:
 *
 *   - mints + parses the `mission:<id>` URN consistently with the
 *     workflow YAML stamper,
 *   - builds `KnowledgeCard` instances representing the Mission
 *     (title · intent · sourceTaskCount · originating workflows),
 *   - exposes a typed `KgsMissionWriter` seam so `register-all` can
 *     write the card alongside the TOX Mission row in one
 *     `RegisterAllDeps` injection.
 *
 * Conservative seed values:
 *   - `kind: 'note'` — Missions are free-form goal clusters; a more
 *     specialised kind (e.g. a future `'mission'` value) can land
 *     later without a schema migration.
 *   - `nature: 'principle'` — a mission is a guiding goal, not a
 *     fact / metric / opinion. `'principle'` is the closest match in
 *     the 9-nature enum.
 *   - `reliability: 'verified'` — the user explicitly approved the
 *     intake (FU-I7d swipe + Register button), so the mission has
 *     been cross-checked at least once by the user. Falls within the
 *     `SourceReliability` enum's 'verified' bucket.
 *
 * Cross-ref:
 *   src/workflow-runtime/types.ts (WorkflowMeta · `_meta.missionId`)
 *   src/intake-plane/register-all.ts (wires this writer)
 *   src/knowledge/kgs/intake.ts (sibling — UserIntentEvent → card)
 */

import { createKnowledgeCard } from './intake.js';
import type { KnowledgeCard } from './types.js';

/** URN prefix that pairs with `WorkflowMeta.missionId`. Imported by
 *  any consumer that needs to round-trip the URN. */
export const MISSION_CARD_ID_PREFIX = 'mission:' as const;

/** Build the canonical card id for a given TOX Mission row id.
 *  Always lowercase prefix · no whitespace · idempotent (passing in
 *  an already-prefixed value returns it unchanged). */
export function mintMissionCardId(missionId: string): string {
  const trimmed = missionId.trim();
  if (!trimmed) throw new RangeError('mintMissionCardId: empty missionId');
  if (trimmed.startsWith(MISSION_CARD_ID_PREFIX)) return trimmed;
  return `${MISSION_CARD_ID_PREFIX}${trimmed}`;
}

/** Extract the raw TOX Mission id from a `mission:<id>` URN.
 *  Returns null when the input does not match the URN pattern (so
 *  callers can early-return rather than throw on stray ids). */
export function parseMissionCardId(cardId: string): string | null {
  if (typeof cardId !== 'string') return null;
  if (!cardId.startsWith(MISSION_CARD_ID_PREFIX)) return null;
  const rest = cardId.slice(MISSION_CARD_ID_PREFIX.length).trim();
  return rest.length > 0 ? rest : null;
}

export interface CreateMissionCardInput {
  /** TOX Mission row id (`m-<slug>`). */
  missionId: string;
  /** Mission title — surfaces in the FTS5 bm25_text + the card UI. */
  title: string;
  /** Free-form mission intent (1-2 sentences). */
  intent: string;
  /** Originating intake submission id, when known. Stamped on the
   *  card so KGS consumers can scope queries to a single intake. */
  intakeId?: string;
  /** Workflow YAML names (or absolute paths) the intake pipeline
   *  produced for this mission. Stored as `relatedIds` so KGS
   *  traversal can hop from mission → workflows in one query. */
  sourceWorkflowIds?: readonly string[];
  /** Count of TOX Task rows this mission spawned. Useful for the
   *  M4-3 endpoint's `taskCount` field. */
  sourceTaskCount?: number;
  /** Test seam — deterministic clock. */
  now?: number;
}

/** Build the KGS Mission card without writing it. Pure — every
 *  field derives from the input + the seed defaults documented at
 *  the top of the module. Used by `register-all` and by unit
 *  tests that need to assert the card shape. */
export function createMissionCard(input: CreateMissionCardInput): KnowledgeCard {
  const cardId = mintMissionCardId(input.missionId);
  const bodyLines = [input.intent];
  if (typeof input.sourceTaskCount === 'number') {
    bodyLines.push(`tasks: ${input.sourceTaskCount}`);
  }
  if (input.sourceWorkflowIds && input.sourceWorkflowIds.length > 0) {
    bodyLines.push(`workflows: ${input.sourceWorkflowIds.join(', ')}`);
  }
  if (input.intakeId) {
    bodyLines.push(`intake: ${input.intakeId}`);
  }
  return createKnowledgeCard({
    id: cardId,
    title: input.title,
    body: bodyLines.join('\n'),
    nature: 'principle',
    kind: 'note',
    source: { kind: 'mission', missionId: input.missionId },
    missionId: input.missionId,
    reliability: 'verified',
    domain: 'intake',
    relatedIds: input.sourceWorkflowIds && input.sourceWorkflowIds.length > 0
      ? Object.freeze([...input.sourceWorkflowIds])
      : undefined,
    tags: ['intake', 'mission'],
    ...(typeof input.now === 'number' ? { now: input.now } : {}),
  });
}

/** Minimal write surface — keeps `register-all` decoupled from the
 *  concrete `KgsSqliteStore` (mirrors the `KgsKeywordLookup` pattern
 *  used by `keyword-crawl-kgs.ts`). The production singleton
 *  (`kgsStoreSingleton()`) satisfies this interface automatically. */
export interface KgsMissionWriter {
  writeCard(card: KnowledgeCard): void;
}
