import { randomUUID } from 'node:crypto';
import { realpath } from 'node:fs/promises';
import { isAbsolute, relative, resolve, sep } from 'node:path';
import { runGoalLoop, type CoreTurnContext, type CoreTurnDispatchTool, type GoalLoopOptions } from '../../core-turn/index.js';
import { debug } from '../../debug/log.js';
import type { LLMMessage, LLMToolSpec } from '../../llm.js';
import { buildAstGrepTool, dispatchAstGrep, hasAstGrep } from './ast-grep.js';
import { buildGlobTool, dispatchGlob } from './glob.js';
import { buildGrepTool, dispatchGrep } from './grep.js';
import { buildListDirTool, dispatchListDir } from './list-dir.js';
import { buildReadTool, dispatchRead } from './read.js';

export const PERSISTENT_GROUNDING_MAX_ITERATIONS = 4;
export const PERSISTENT_GROUNDING_TOOL_NAMES = ['Grep', 'Glob', 'ListDir', 'AstGrep', 'Read'] as const;

export interface PersistentGroundingDeps {
  runGoalLoop?: typeof runGoalLoop;
  dispatchTool?: CoreTurnDispatchTool;
  maxIterations?: number;
  sessionId?: string;
  hasAstGrep?: () => boolean;
  relativePath?: (from: string, to: string) => string;
  /** Terms generated by an upstream grounding consumer; the loop must prioritize them for code discovery. */
  terms?: string[];
}

export interface PersistentGroundingResult {
  files: string[];
  /** Verbatim completion-evidence lines for candidates that the loop actually Read. */
  evidence: string[];
  iterations: number;
  stopReason: string;
}

/** Shared read-only source-discovery catalog used by any grounding consumer. */
export function persistentGroundingTools(deps: Pick<PersistentGroundingDeps, 'hasAstGrep'> = {}): LLMToolSpec[] {
  const astGrepAvailable = (deps.hasAstGrep ?? hasAstGrep)();
  return [
    buildGrepTool(),
    buildGlobTool(),
    buildListDirTool(),
    ...(astGrepAvailable ? [buildAstGrepTool()] : []),
    buildReadTool(),
  ];
}

const READ_ONLY_TOOL_NAMES = new Set<string>(PERSISTENT_GROUNDING_TOOL_NAMES);

async function scopedPath(args: Record<string, unknown>, key: 'path' | 'file_path', cwd: string): Promise<Record<string, unknown> | null> {
  const value = args[key];
  if (value !== undefined && (typeof value !== 'string' || !value.trim() || isAbsolute(value))) return null;
  const root = await realpath(cwd).catch(() => null);
  if (!root) return null;
  const path = resolve(root, typeof value === 'string' ? value : '.');
  const resolvedPath = await realpath(path).catch(() => null);
  if (!resolvedPath) return null;
  const fromRoot = relative(root, resolvedPath);
  if (fromRoot === '..' || fromRoot.startsWith(`..${sep}`) || isAbsolute(fromRoot)) return null;
  return { ...args, [key]: resolvedPath };
}

function dispatchReadOnly(name: string, args: Record<string, unknown>, cwd: string): Promise<unknown> {
  if (name === 'Grep') return dispatchGrep(args);
  if (name === 'Glob') return dispatchGlob(args);
  if (name === 'ListDir') return dispatchListDir(args);
  if (name === 'AstGrep') return dispatchAstGrep(args, { cwd });
  if (name === 'Read') return dispatchRead(args);
  return Promise.resolve({ error: `persistent grounding refuses non-readonly tool: ${name}` });
}

function isToolError(result: unknown): boolean {
  return typeof result === 'object' && result !== null && 'error' in result;
}

function isReadResult(result: unknown): result is {
  output: string;
  linesRead: number;
  totalLines: number;
  totalBytes: number;
  truncated: boolean;
  kind: 'text' | 'image' | 'pdf' | 'binary';
} {
  if (typeof result !== 'object' || result === null || isToolError(result)) return false;
  const value = result as Record<string, unknown>;
  return typeof value.output === 'string'
    && typeof value.linesRead === 'number'
    && typeof value.totalLines === 'number'
    && typeof value.totalBytes === 'number'
    && typeof value.truncated === 'boolean'
    && (value.kind === 'text' || value.kind === 'image' || value.kind === 'pdf' || value.kind === 'binary');
}

export function normalizeRepositoryRelativePath(path: string): string {
  return path.replaceAll('\\', '/');
}

function guardedDispatchTool(
  cwd: string,
  delegate?: CoreTurnDispatchTool,
  readFiles = new Set<string>(),
  relativePath: (from: string, to: string) => string = relative,
): CoreTurnDispatchTool {
  return async (name, args, callCtx) => {
    if (!READ_ONLY_TOOL_NAMES.has(name)) return { error: `persistent grounding refuses non-readonly tool: ${name}` };
    const rawArgs = args as Record<string, unknown>;
    const key = name === 'Read' ? 'file_path' : 'path';
    const scopedArgs = await scopedPath(rawArgs, key, cwd);
    if (!scopedArgs) return { error: `persistent grounding refuses path outside cwd: ${String(rawArgs[key])}` };
    const result = delegate
      ? await delegate(name, scopedArgs, callCtx)
      : await dispatchReadOnly(name, scopedArgs, cwd);
    if (name === 'Read' && isReadResult(result)) {
      readFiles.add(normalizeRepositoryRelativePath(relativePath(await realpath(cwd), String(scopedArgs.file_path))));
    }
    return result;
  };
}

const EVIDENCE_PATH_PATTERN = /(^|[^A-Za-z0-9_./\\-])((?:[A-Za-z0-9_.-]+\/)+[A-Za-z0-9_.-]+\.(?:ts|tsx|js|mjs|cjs|kt|kts|swift|py|sh|bash))(?=$|[^A-Za-z0-9_./\\-])/g;
const ALLOWED_EVIDENCE_ROOTS = new Set(['src', 'scripts', 'test', 'tests', 'packages', 'apps']);

/** A defensive snapshot lets tests observe the policy without changing the runtime source of truth. */
export function allowedEvidenceRoots(): ReadonlySet<string> {
  return new Set(ALLOWED_EVIDENCE_ROOTS);
}

function repositoryRelativeCodePaths(line: string): string[] {
  return Array.from(line.matchAll(EVIDENCE_PATH_PATTERN), (match) => normalizeRepositoryRelativePath(match[2]!));
}

/** A whole repository-relative path is inside a code root only when its first segment is an allowed root; prefix (`docs/src/x`) and suffix (`notsrc/x`) impersonation therefore fail. */
function isCodeRootPath(path: string): boolean {
  return ALLOWED_EVIDENCE_ROOTS.has(path.split('/')[0]!);
}

function containsMeaningfulEvidenceText(line: string, paths: readonly string[]): boolean {
  const nonPathText = paths.reduce((text, path) => text.replaceAll(path, ''), line);
  return nonPathText.replace(/[\s\-–—•*.,:;|()[\]{}]/g, '').length > 0;
}

export interface EvidenceRejection {
  readonly noPath: number;
  readonly outsideRoot: number;
  readonly notRead: number;
  readonly noMeaningfulText: number;
  readonly samples: readonly string[];
}

const EVIDENCE_REJECTION_SAMPLE_LIMIT = 3;
const EVIDENCE_REJECTION_SAMPLE_PREFIX_LENGTH = 200;

function rejectionSample(value: string): string {
  return value.slice(0, EVIDENCE_REJECTION_SAMPLE_PREFIX_LENGTH);
}

function verifiedEvidenceFromCompletion(evidence: string, readFiles: Set<string>): { files: string[]; evidence: string[]; rejection: EvidenceRejection } {
  const lines = evidence.split(/\r?\n/).filter((line) => line.trim());
  const rejection: {
    noPath: number;
    outsideRoot: number;
    notRead: number;
    noMeaningfulText: number;
    samples: string[];
  } = {
    noPath: 0,
    outsideRoot: 0,
    notRead: 0,
    noMeaningfulText: 0,
    samples: [],
  };
  const addSample = (sample: string) => {
    if (rejection.samples.length < EVIDENCE_REJECTION_SAMPLE_LIMIT) rejection.samples.push(rejectionSample(sample));
  };
  const verifiedLines = lines.filter((line) => {
    const paths = repositoryRelativeCodePaths(line);
    const hasPath = paths.length > 0;
    const insideRoot = paths.every(isCodeRootPath);
    const unreadPaths = paths.filter((path) => !readFiles.has(path));
    const hasMeaningfulText = containsMeaningfulEvidenceText(line, paths);
    if (!hasPath) rejection.noPath += 1;
    if (!insideRoot) rejection.outsideRoot += 1;
    if (unreadPaths.length > 0) rejection.notRead += 1;
    if (!hasMeaningfulText) rejection.noMeaningfulText += 1;
    if (!hasPath || !insideRoot || unreadPaths.length > 0 || !hasMeaningfulText) addSample(unreadPaths[0] ?? line);
    return hasPath && insideRoot && unreadPaths.length === 0 && hasMeaningfulText;
  });
  const files = Array.from(new Set(verifiedLines.flatMap(repositoryRelativeCodePaths)));
  return { files, evidence: verifiedLines, rejection };
}

function groundingMessages(goal: string, terms: readonly string[]): LLMMessage[] {
  return [{
    role: 'user',
    content: [
      'Repository grounding task: find existing implementation candidates for this request.',
      ...(terms.length ? [`Prioritize these upstream-generated search terms when choosing code-discovery queries: ${terms.join(', ')}`] : []),
      'Use Grep for text, Glob for filename discovery, ListDir for directory shape, AstGrep for syntax-aware queries, then Read the most relevant files. If the first search is weak, inspect its result and search again with better English identifiers or call-path terms.',
      'Do not edit, write, run shell commands, or use any tool other than Grep, Glob, ListDir, AstGrep, and Read.',
      `When the evidence is sufficient, call update_goal with status=complete and evidence containing only verified repository-relative ${Array.from(ALLOWED_EVIDENCE_ROOTS, (root) => `${root}/`).join(' or ')} file paths plus the reason each is relevant.`,
      `Request: ${goal}`,
    ].join('\n'),
  }];
}

/** Bounded, shared, read-only grounding loop. Failure or no candidates returns null. */
export async function groundPersistently(goal: string, cwd: string, deps: PersistentGroundingDeps = {}): Promise<PersistentGroundingResult | null> {
  const startedAt = performance.now();
  const durationMs = () => {
    const elapsed = performance.now() - startedAt;
    return Number.isFinite(elapsed) && elapsed >= 0 ? elapsed : 0;
  };
  const maxIterations = Math.min(
    PERSISTENT_GROUNDING_MAX_ITERATIONS,
    Math.max(1, deps.maxIterations ?? PERSISTENT_GROUNDING_MAX_ITERATIONS),
  );
  const sessionId = deps.sessionId ?? `grounding-${randomUUID()}`;
  const astGrepAvailable = (deps.hasAstGrep ?? hasAstGrep)();
  if (!astGrepAvailable) debug.log('grounding.persistent', 'tool-unavailable', { sessionId, tool: 'AstGrep' }, { level: 'warn' });
  const toolCalls: Record<string, number> = {};
  let completedIterations: number | undefined;
  try {
    const loop = deps.runGoalLoop ?? runGoalLoop;
    let completionEvidence = '';
    const readFiles = new Set<string>();
    const ctx: CoreTurnContext = {
      sessionId,
      messages: groundingMessages(goal, deps.terms ?? []),
      tools: persistentGroundingTools(deps),
      dispatchTool: guardedDispatchTool(cwd, deps.dispatchTool, readFiles, deps.relativePath),
      signal: new AbortController().signal,
      maxToolTurns: 4,
      callbacks: {
        onToolCall: (call) => {
          toolCalls[call.name] = (toolCalls[call.name] ?? 0) + 1;
          if (call.name === 'update_goal' && call.args.status === 'complete' && typeof call.args.evidence === 'string') completionEvidence = call.args.evidence;
        },
        onTurnComplete: () => {
          completedIterations = (completedIterations ?? 0) + 1;
        },
      },
    };
    const options: GoalLoopOptions = { maxIterations, objective: `Persistent repository grounding: ${goal.slice(0, 200)}` };
    const result = await loop(ctx, options);
    const verified = result.goalComplete && result.stopReason === 'goal_complete'
      ? verifiedEvidenceFromCompletion(completionEvidence, readFiles)
      : {
        files: [],
        evidence: [],
        rejection: { noPath: 0, outsideRoot: 0, notRead: 0, noMeaningfulText: 0, samples: [] },
      };
    try {
      debug.log('grounding.persistent', 'finished', {
        sessionId,
        maxIterations,
        durationMs: durationMs(),
      iterations: result.iterations,
      stopReason: result.stopReason,
      // ⛔ 「끝났다」가 두 뜻이다 — ⓐ 스스로 목표를 끝냈다 ⓑ 턴이 «그냥» 끝났다.
      //   📏 2026-08-11 72차 전수(400건): 후보 0인 finished 가 5건이고 ***다섯 다 end_turn*** 이었다.
      //   그 둘을 한 이름에 두면 「접지는 성공인데 코드가 0」이라는 «없는 수수께끼»가 생긴다.
      outcome: result.goalComplete && result.stopReason === 'goal_complete' ? 'goal-complete' : 'stopped-without-goal',
      candidates: verified.files,
      candidateCount: verified.files.length,
      evidenceCount: verified.evidence.length,
      evidenceRejection: verified.rejection,
        toolCalls,
      });
    } catch {
      // Completion telemetry must not prevent a successful grounding result.
    }
    return {
      files: verified.files,
      evidence: verified.evidence,
      iterations: result.iterations,
      stopReason: result.stopReason,
    };
  } catch (error) {
    try {
      debug.log('grounding.persistent', 'failed', {
        sessionId,
        maxIterations,
        durationMs: durationMs(),
        toolCalls,
        ...(completedIterations === undefined ? {} : { iterations: completedIterations }),
        reason: error instanceof Error ? error.message.slice(0, 200) : String(error).slice(0, 200),
      }, { level: 'warn' });
    } catch {
      // Failure telemetry must not prevent the grounding failure fallback.
    }
    return null;
  }
}
